checker:
  query:
    url: https://pk.api.onliner.by/search/apartments
    boundsLbLatParamName: bounds[lb][lat]
    boundsLbLongParamName: bounds[lb][long]
    boundsRtLatParamName: bounds[rt][lat]
    boundsRtLongParamName: bounds[rt][long]
    wallingParamName: walling[]
    pageParamName: page
    walling: brick,monolith
    boundsLbLat: 53.779963673435276
    boundsLbLong: 27.248840332031254
    boundsRtLat: 54.01543502648378
    boundsRtLong: 27.875747680664066
    priceMin: 44000
    priceMax: 65000
    priceMinParamName: price[min]
    priceMaxParamName: price[max]
    currency: usd
    currencyParamName: currency
spring:
  profiles:
    active: onliner
  data:
    mongodb:
      uri: mongodb://localhost:27017/realtchecker
cron:
  check-schedule: 0 0 12,21 * * ?
server:
  port: 8099