checker:
  query:
    url: https://pk.api.onliner.by/search/apartments
    boundsLbLatParamName: bounds[lb][lat]
    boundsLbLongParamName: bounds[lb][long]
    boundsRtLatParamName: bounds[rt][lat]
    boundsRtLongParamName: bounds[rt][long]
    wallingParamName: walling[]
    pageParamName: page
    walling: brick,monolith
    boundsLbLat: 53.779963673435276
    boundsLbLong: 27.248840332031254
    boundsRtLat: 54.01543502648378
    boundsRtLong: 27.875747680664066
    priceMin: 44000
    priceMax: 65000
    priceMinParamName: price[min]
    priceMaxParamName: price[max]
    currency: usd
    currencyParamName: currency
  store:
    path: e:\projects\home\realtchecker\onlinerby\analysis
  email:
    header:
      prefix: onliner.by
spring:
  profiles:
    active: onliner
  mail:
    debug: true
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    username: kulaginsp
    password: ENC(gJtATA3b7wFTA7F5Kluyr9fjBFD/NFFWS27r5wNRLAw=)
    to: kulaginatm@gmail.com,kulaginsp@gmail.com
  data:
    mongodb:
      uri: mongodb://localhost:27017/realtchecker
cron:
  check-schedule: 0 0 8,12,17,21 * * ?
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
server:
  port: 8098
