checker:
  query:
    url: https://realt.by/sale/flats/
    boundsLbLatParamName: bounds[lb][lat]
    boundsLbLongParamName: bounds[lb][long]
    boundsRtLatParamName: bounds[rt][lat]
    boundsRtLongParamName: bounds[rt][long]
    wallingParamName: walling[]
    pageParamName: page
    walling: brick
    boundsLbLat: 53.779963673435276
    boundsLbLong: 27.248840332031254
    boundsRtLat: 54.01543502648378
    boundsRtLong: 27.875747680664066
    priceMin: 45250
    priceMax: 60000
    priceMinParamName: price[min]
    priceMaxParamName: price[max]
    currency: usd
    currencyParamName: currency
    realtby:
      search_hash: eJxtzkEOgyAQQNHTwBqQsbjooug9CMJYTZpKENP09iJtdOOGyfyXSUjz520mT0Ajge4OnAka4uTypp8lyeoIrxJqRcd5XdCkb8D/YR5sN9IxottL54c/Ll2cXl5OzYJpDZkiOhMwmmB/XwJ22rgH0YOSFlXjG/CDsM76AW8KasRKWoYbLmFDCQ==

  store:
    path: e:\projects\home\realtchecker\realtby\analysis
  email:
    header:
      prefix: realt.by
spring:
  profiles:
    active: realt-by
  mail:
    debug: true
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    username: kulaginsp
    password: ENC(gJtATA3b7wFTA7F5Kluyr9fjBFD/NFFWS27r5wNRLAw=)
    to: kulaginsp@gmail.com,kulaginatm@gmail.com
cron:
  check-schedule: 0 0 8-22 * * ?
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
server:
  port: 8198