checker:
  query:
    urls:
      page-hash-url: https://realt.by/sale/flats/search/#tabs
      get-hash-url: https://realt.by/
      search-url: https://realt.by/sale/flats/
    parameters:
      type: count
      "[s[price][le]]": 73
      "[s[price][ge]]": 40
      "[s[house_type][e][]]": м,к,кб
      "[s[town_name][like][0]]": Минск
      "[s[town_id][e]]": 5102
      "[s[storey][fe]]": storeys
      "[x_uedbflat_pi2[rec_per_page]]": 50
      eID: tx_uedbcore_mapApi
      tid: 1
      R: 0
    headers:
      User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/71.0.3578.80 Chrome/71.0.3578.80 Safari/537.36
  store:
    path: ./realtby/analysis
  email:
    header:
      prefix: realt.by
spring:
  profiles:
    active: realt-by
  mail:
    debug: true
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    username: kulaginsp
    to: kulaginatm@gmail.com,kulaginsp@gmail.com
cron:
  check-schedule: 0 0 8,12,17,21 * * ?
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
server:
  port: 8198

debug: true