service:
  onliner:
    enabled: true
    url: https://pk.api.onliner.by/search/apartments
    boundsLbLatParamName: bounds[lb][lat]
    boundsLbLongParamName: bounds[lb][long]
    boundsRtLatParamName: bounds[rt][lat]
    boundsRtLongParamName: bounds[rt][long]
    wallingParamName: walling[]
    pageParamName: page
    walling: brick
    boundsLbLat: 53.779963673435276
    boundsLbLong: 27.248840332031254
    boundsRtLat: 54.01543502648378
    boundsRtLong: 27.875747680664066
    priceMin: 45000
    priceMax: 95000
    priceMinParamName: price[min]
    priceMaxParamName: price[max]
    currency: usd
    currencyParamName: currency
    query-delay: 1500ms
  realtby:
    enabled: true
    query-delay: 2000ms
    search-hash: eJxtjssOgyAURL8G1jzEwsKFyn8QCtdqapX4SNO/L9BEk8bNzGRO5uZu83syk30BEs04PKPpmEi0CmmCVJu0kVk10hRJmnONwzK4tHqkTVXwoxhzUUrcz/sKZvuE1P5fbtpLTg9eX3J28qwUmxW2PUS0gDMBFhPs7yVOTtangt2FLCxI5ZXwHbPO+g5uUpQAvLAEvhFQS9w=
    urls:
      page-hash-url: https://realt.by/sale/flats/search/#tabs
      get-hash-url: https://realt.by/
      search-url: https://realt.by/sale/flats/
    parameters:
      type: count
      "[s[price][ge]]": 45
      "[s[price][le]]": 95
      "[s[house_type][e][]]": м,к,кб
      "[s[town_name][like][0]]": Минск
      "[s[town_id][e]]": 5102
      "[s[storey][fe]]": storeys
      "[x_uedbflat_pi2[rec_per_page]]": 50
      eID: tx_uedbcore_mapApi
      tid: 1
      R: 0
    headers:
      User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/71.0.3578.80 Chrome/71.0.3578.80 Safari/537.36
cron:
  check-schedule: 0 0 11,19 * * ?
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:demo@192.168.100.35:30050/realtchecker?authSource=admin