service:
  onliner:
    query:
      url: https://pk.api.onliner.by/search/apartments
      boundsLbLatParamName: bounds[lb][lat]
      boundsLbLongParamName: bounds[lb][long]
      boundsRtLatParamName: bounds[rt][lat]
      boundsRtLongParamName: bounds[rt][long]
      wallingParamName: walling[]
      pageParamName: page
      walling: brick
      boundsLbLat: 53.779963673435276
      boundsLbLong: 27.248840332031254
      boundsRtLat: 54.01543502648378
      boundsRtLong: 27.875747680664066
      priceMin: 45250
      priceMax: 68000
      priceMinParamName: price[min]
      priceMaxParamName: price[max]
      currency: usd
      currencyParamName: currency
    realtby:
      search_hash: eJxtjssOgyAURL8G1jzEwsKFyn8QCtdqapX4SNO/L9BEk8bNzGRO5uZu83syk30BEs04PKPpmEi0CmmCVJu0kVk10hRJmnONwzK4tHqkTVXwoxhzUUrcz/sKZvuE1P5fbtpLTg9eX3J28qwUmxW2PUS0gDMBFhPs7yVOTtangt2FLCxI5ZXwHbPO+g5uUpQAvLAEvhFQS9w=
cron:
  check-schedule: 0 0 8-22 * * ?
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
server:
  port: 8099

spring:
  data:
    mongodb:
      uri: mongodb://root:demo@192.168.100.35:30050/realtchecker?authSource=admin